SPECIFICATION.md
In the specified file: https://github.com/yearn/tokenized-strategy/blob/master/SPECIFICATION.md
At lines: 103, 104
It mentions that:
```
If totalAssets < newTotalAssets: the vault will record a loss
If totalAssets > newTotalAssets: the vault will record a profit
```
which should be :
```
If totalAssets < newTotalAssets: the vault will record a profit
If totalAssets > newTotalAssets: the vault will record a loss
```
Fixes #61
=> fix: erroneous profit and loss accounting in specification

foundry.toml, src/TokenizedStrategy.sol, src/test/AccessControl.t.sol, src/test/ProfitLocking.t.sol
Allow profit unlocking to be set to 0 to allow instant unlocks
#60
=> build: instant profit unlocking

.solhint.json, foundry.toml, src/BaseTokenizedStrategy.sol, src/TokenizedStrategy.sol, src/interfaces/IEvents.sol, src/interfaces/ITokenizedStrategy.sol, src/test/AccessControl.t.sol, src/test/CustomImplementation.t.sol, src/test/Shutdown.t.sol, src/test/mocks/IMockStrategy.sol, src/test/mocks/MockStrategy.sol, src/test/utils/Setup.sol
- Add different revert messages for each modifier.
- add a new emergencyAdmin, getters, setters and modifiers that can shutdown strategy and call emergencyWithdraw
- Emergency Admin defaults to address(0) and must be set manually.
- moved the max checks each to its own function to avoid rounding issues and give correct revert messages.
#59
=> build: update modifiers

foundry.toml, src/TokenizedStrategy.sol, src/test/FaultyStrategy.t.sol, src/test/mocks/IMockStrategy.sol, src/test/mocks/MockFaultyStrategy.sol
- Use the same logic for idle and debt updates for both tend and emergency withdraws.
- Make sure it updates accurately even if nothing changed during that specific call.
- Enforce that totalAssets after == totalAssets before
- 
=> build: balance updates

src/TokenizedStrategy.sol, src/test/ProfitLocking.t.sol
Please include a summary of the change and/or which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> feat: dont burn unlocked

foundry.toml, src/BaseStrategy.sol, src/TokenizedStrategy.sol, src/interfaces/ITokenizedStrategy.sol, src/test/Accounting.t.sol, src/test/CustomImplementation.t.sol, src/test/FaultyStrategy.t.sol, src/test/InvariantsSingleStrategy.t.sol, src/test/mocks/MockFaultyStrategy.sol, src/test/mocks/MockIlliquidStrategy.sol, src/test/utils/BaseInvariant.sol, src/test/utils/Setup.sol
Only track totalAssets and not totalIdle and totalDebt.
-Makes everything cheaper and simpler and allows assets to move around outside normal functionality.
=> feat: just track total assets

SPECIFICATION.md
Just change a typo in the Tokenized Strategy Specs
=> fix: typo in specification

.gitmodules, src/TokenizedStrategy.sol, src/test/CustomImplementation.t.sol, src/test/e2e.t.sol, src/test/utils/Setup.sol
- Use convertToShares instead of previewWithdraw in maxRedeem.
- This will round down instead of up. Eliminating a potential issue caused by double rounding in which the convertToAssets in `redeem` will return a value slightly higher than the avialableWithdrawLimit
- also bumped OZ version
=> fix: max redeem rounding

src/TokenizedStrategy.sol
Please include a summary of the change and/or which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> feat: remove internal preview functions

.vscode/settings.json, src/BaseStrategy.sol, src/TokenizedStrategy.sol, src/interfaces/IEvents.sol, src/interfaces/ITokenizedStrategy.sol, src/test/AccessControl.t.sol, src/test/ERC20Std.t.sol, src/test/mocks/MockStorage.sol, src/test/utils/Setup.sol
- change init -> initialization to avoid python/vyper collisions
- rename functions used by modifiers to 'require' instead of 'is' for clarity.
- organize events
- Pack struct tighter -- Removed 3 slots.
- remove internal preview functions and add rounding param to internal converTo functions
=> fix: formatting

SPECIFICATION.md, src/TokenizedStrategy.sol, src/interfaces/ITokenizedStrategy.sol, src/test/AccessControl.t.sol, src/test/e2e.t.sol, src/test/utils/Setup.sol
- Remove MIN_FEE
- Use 1 and 2 for reentrancy instead of true and false
- remove internal preview functions and add rounding param to conversions
- MAke the Factory immutable not constant for easier deployment
=> fix: minor changes

src/TokenizedStrategy.sol, src/test/ProfitLocking.t.sol
- improved performance of the `report` function for gas savings.
- only use convertToShares once per report
- Only burn or mint shares to the strategy once during each report based on the end state
- only update lastReport once.
- removes up to 3 extra sstore's
=> feat: lower report costs

SPECIFICATION.md
Correct typos in the Tokenized Strategy Specs
=> fix: correct typos

SPECIFICATION.md
Update function signatures to match the implementation of `BaseStrategy.sol`.
=> docs: correct function signatures in SPECIFICATION.md 

src/TokenizedStrategy.sol, src/test/Accounting.t.sol, src/test/ERC4626Std.t.sol, src/test/handlers/StrategyHandler.sol
Pass max uint into deposit in order to deposit the full balance of the caller.
=> feat: max deposit

src/TokenizedStrategy.sol, src/interfaces/ITokenizedStrategy.sol, src/test/CustomImplementation.t.sol
Adds a `maxLoss` variable for maxRedeem and maxWithdraw that matches the multi strategy vaults ABI and the withdraw and redeem functions. Variable is currently not used.
=> chore: match vault abi

src/TokenizedStrategy.sol, src/interfaces/ITokenizedStrategy.sol, src/test/AccessControl.t.sol
Allow management to update the strategy name
=> feat: update name

src/TokenizedStrategy.sol, src/test/mocks/MockStorage.sol
- Change domain separator to use "Yearn Vault" instead of name since name can now be updated.
- Remove the cached permit variables since they cannot be immutable. Better of recalculating
=> chore: update domain separator

src/TokenizedStrategy.sol
Don't cast the name through bytes before keccack
=> fix: permit constants

src/TokenizedStrategy.sol, src/test/Accounting.t.sol
Still allow deposits to work if totalSupply == 0 but totalAssets > 0. Just make PPS == 1.
This can happen due to the profit unlocking if all shares are redeemed while some profit is still unlocking, at the end of the unlock time totalAssets >0 but totalSupply == 0.
- Still return 0 in convertToShares if totalSupply > 0 but totalAssets == 0. Meaning a full loss.
- Optimize to not cache totalAssets_ until needed
- Add the check for share receiver to the maxDeposit/maxMint checks instead. So that the view functions are more accurate.
- Update the variable name from `owner` => `receiver` to be more accurate
=> fix: deposit flow
